import { useEffect, useState } from 'react';
import { listAlerts, updateAlert, escalateAlert, type Alert } from '../api/alerts';
import { AlertTriangle, Filter, CheckCircle, ArrowUpCircle, Clock } from 'lucide-react';

const severityStyles: Record<string, string> = {
  critical: 'bg-red-500/10 text-red-400 border-red-500/20',
  high: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  medium: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
  low: 'bg-matrix-500/10 text-matrix-400 border-matrix-500/20',
  informational: 'bg-gray-500/10 text-gray-400 border-gray-500/20',
};

const statusStyles: Record<string, string> = {
  open: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  acknowledged: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  resolved: 'bg-matrix-500/10 text-matrix-400 border-matrix-500/20',
  dismissed: 'bg-gray-500/10 text-gray-400 border-gray-500/20',
};

export default function Alerts() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState('');
  const [filterSeverity, setFilterSeverity] = useState('');
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    try {
      const params: Record<string, string> = {};
      if (filterStatus) params.status = filterStatus;
      if (filterSeverity) params.severity = filterSeverity;
      params.limit = '200';

      const data = await listAlerts(params as any);
      setAlerts(data);
    } catch (err) {
      console.error('Failed to load alerts:', err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); }, [filterStatus, filterSeverity]);

  const handleStatusChange = async (alertId: string, status: string) => {
    setActionLoading(alertId);
    try {
      await updateAlert(alertId, { status });
      setAlerts(alerts.map((a) => a.id === alertId ? { ...a, status } : a));
    } catch (err) {
      console.error('Failed to update alert:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const handleEscalate = async (alertId: string) => {
    setActionLoading(alertId);
    try {
      await escalateAlert(alertId);
      setAlerts(alerts.map((a) => a.id === alertId ? { ...a, status: 'acknowledged' } : a));
    } catch (err) {
      console.error('Failed to escalate:', err);
    } finally {
      setActionLoading(null);
    }
  };

  const severity = ['critical', 'high', 'medium', 'low', 'informational'];
  const statuses = ['open', 'acknowledged', 'resolved', 'dismissed'];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Alerts</h1>
          <p className="text-gray-500 mt-1">Security alerts generated by the threat detection system</p>
        </div>
      </div>

      {/* Filter bar */}
      <div className="flex flex-wrap gap-3">
        <div className="flex items-center gap-2 bg-surface-900 border border-surface-800 rounded-lg p-1">
          <Filter className="w-4 h-4 text-gray-500 ml-2" />
          <select
            value={filterSeverity}
            onChange={(e) => setFilterSeverity(e.target.value)}
            className="bg-transparent text-sm text-gray-300 px-2 py-1.5 outline-none"
          >
            <option value="">All Severities</option>
            {severity.map((s) => (
              <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>
            ))}
          </select>
          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="bg-transparent text-sm text-gray-300 px-2 py-1.5 outline-none"
          >
            <option value="">All Statuses</option>
            {statuses.map((s) => (
              <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>
            ))}
          </select>
        </div>
        {(filterStatus || filterSeverity) && (
          <button
            onClick={() => { setFilterStatus(''); setFilterSeverity(''); }}
            className="text-xs text-cyber-400 hover:underline"
          >
            Clear filters
          </button>
        )}
      </div>

      {/* Alert list */}
      {loading ? (
        <div className="flex justify-center py-16">
          <div className="w-8 h-8 border-2 border-cyber-400 border-t-transparent rounded-full animate-spin" />
        </div>
      ) : alerts.length === 0 ? (
        <div className="text-center py-16 bg-surface-900 rounded-xl border border-surface-800">
          <CheckCircle className="w-12 h-12 text-matrix-400 mx-auto mb-3" />
          <p className="text-gray-500">No alerts match your filters</p>
          <p className="text-gray-600 text-sm mt-1">All clear — no security alerts at the moment</p>
        </div>
      ) : (
        <div className="space-y-3">
          {alerts.map((alert) => (
            <div
              key={alert.id}
              className="bg-surface-900 rounded-xl border border-surface-800 p-5 hover:border-surface-700 transition-all"
            >
              <div className="flex items-start gap-4">
                <div className={`p-2.5 rounded-lg border ${severityStyles[alert.severity] || severityStyles.informational}`}>
                  <AlertTriangle className="w-5 h-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="text-sm font-semibold text-gray-200">{alert.title}</h3>
                    <span className={`px-2 py-0.5 rounded text-xs font-medium border capitalize ${severityStyles[alert.severity]}`}>
                      {alert.severity}
                    </span>
                    <span className={`px-2 py-0.5 rounded text-xs font-medium border capitalize ${statusStyles[alert.status]}`}>
                      {alert.status}
                    </span>
                  </div>
                  {alert.description && (
                    <p className="text-sm text-gray-400 mt-2">{alert.description}</p>
                  )}
                  <div className="flex items-center gap-4 mt-3 text-xs text-gray-500">
                    {alert.anomaly_type && (
                      <span className="px-2 py-0.5 rounded bg-surface-800">{alert.anomaly_type}</span>
                    )}
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      {new Date(alert.created_at).toLocaleString()}
                    </span>
                  </div>
                </div>
                <div className="flex flex-col gap-2">
                  {alert.status === 'open' && (
                    <>
                      <button
                        onClick={() => handleStatusChange(alert.id, 'acknowledged')}
                        disabled={actionLoading === alert.id}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium 
                          bg-purple-500/10 text-purple-400 border border-purple-500/20 hover:bg-purple-500/20 transition-all"
                      >
                        <CheckCircle className="w-3.5 h-3.5" />
                        Acknowledge
                      </button>
                      <button
                        onClick={() => handleEscalate(alert.id)}
                        disabled={actionLoading === alert.id}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium 
                          bg-danger-500/10 text-danger-400 border border-danger-500/20 hover:bg-danger-500/20 transition-all"
                      >
                        <ArrowUpCircle className="w-3.5 h-3.5" />
                        Escalate
                      </button>
                    </>
                  )}
                  {alert.status === 'acknowledged' && (
                    <button
                      onClick={() => handleStatusChange(alert.id, 'resolved')}
                      disabled={actionLoading === alert.id}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium 
                        bg-matrix-500/10 text-matrix-400 border border-matrix-500/20 hover:bg-matrix-500/20 transition-all"
                    >
                      <CheckCircle className="w-3.5 h-3.5" />
                      Resolve
                    </button>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
